@if "%DEBUG%" == "" @echo off
@rem This is a placeholder for the Gradle wrapper batch script.
@rem The actual script will be generated by Gradle.
echo "Error: This is a placeholder gradlew.bat script. Please generate the Gradle wrapper."
exit /b 1
